// ============================================================
// SERVIS — kandungan halaman terperinci setiap pakej (/servis/:slug).
// Dwibahasa ms/en. Demo interaktif ambil data contoh dari sini juga.
// Semua nombor dalam demo = REKAAN untuk tunjuk rupa, bukan data sebenar.
// ============================================================

export const SLUGS = ['kilat', 'asas', 'operasi']

// ---- data contoh untuk demo (tak berubah ikut bahasa) ----
// Barang runcit biasa supaya mana-mana peniaga nampak diri dia dalam contoh.
export const DEMO_ITEMS = [
  { sku: 'BRS-005', name: { ms: 'Beras Super 5kg', en: 'Rice 5kg' }, price: 26.5, unit: { ms: 'kampit', en: 'bag' } },
  { sku: 'MYK-001', name: { ms: 'Minyak Masak 1L', en: 'Cooking Oil 1L' }, price: 7.9, unit: { ms: 'botol', en: 'bottle' } },
  { sku: 'GLA-1KG', name: { ms: 'Gula Halus 1kg', en: 'Sugar 1kg' }, price: 3.4, unit: { ms: 'paket', en: 'pack' } },
  { sku: 'TPG-500', name: { ms: 'Tepung Gandum 500g', en: 'Flour 500g' }, price: 2.8, unit: { ms: 'paket', en: 'pack' } },
  { sku: 'MGI-005', name: { ms: 'Mi Segera 5s', en: 'Instant Noodles 5s' }, price: 4.6, unit: { ms: 'pek', en: 'pack' } },
  { sku: 'SUS-397', name: { ms: 'Susu Pekat 397g', en: 'Condensed Milk 397g' }, price: 4.2, unit: { ms: 'tin', en: 'tin' } },
]

export const DEMO_DASH = {
  stats: [
    { key: 'sales', v: 'RM 3,480', d: '+12%' },
    { key: 'orders', v: '47', d: '+5' },
    { key: 'low', v: '9', d: null },
    { key: 'profit', v: 'RM 812', d: '23%' },
  ],
  bars: [42, 58, 35, 71, 64, 88, 96],
  lowStock: [
    { sku: 'BRS-005', name: { ms: 'Beras Super 5kg', en: 'Rice 5kg' }, left: 3, need: 20 },
    { sku: 'MYK-001', name: { ms: 'Minyak Masak 1L', en: 'Cooking Oil 1L' }, left: 5, need: 24 },
    { sku: 'SUS-397', name: { ms: 'Susu Pekat 397g', en: 'Condensed Milk 397g' }, left: 2, need: 36 },
  ],
}

const kilat = {
  ms: {
    kicker: 'Pakej 01',
    name: 'KILAT',
    promise: 'Satu kerja manual yang menyakitkan — saya tukar jadi alat, siap dalam 7 hari.',
    sub: 'Bukan sistem besar. Satu alat yang buat satu kerja, betul-betul elok. Awak guna hari pertama juga.',
    signsLabel: 'Tanda awak perlukan ini',
    signs: [
      'Ada satu kerja yang awak ulang setiap minggu, guna tangan, dan awak benci buat',
      'Maklumat awak duduk dalam Excel atau Google Sheet dan susah nak guna masa sibuk',
      'Awak taip benda yang sama berulang kali dalam WhatsApp',
      'Kadang tersalah taip, tersalah kira, atau tertinggal barang',
    ],
    getsLabel: 'Apa yang awak dapat',
    getsGroups: [
      {
        title: 'Alat itu sendiri',
        items: [
          'Satu alat dengan link sendiri — buka atas telefon, tablet atau laptop',
          'Tak perlu install apa-apa, tak perlu akaun, tak perlu ajar staf guna app baru',
          'Elok atas skrin telefon (kebanyakan orang guna atas telefon)',
          'Pilihan awak tersimpan sendiri — tutup, buka balik, kerja masih ada',
        ],
      },
      {
        title: 'Data awak masuk sekali',
        items: [
          'Saya ambil senarai sedia ada awak — Excel, Google Sheet, PDF, atau senarai WhatsApp',
          'Saya kemas dan susun, awak tak perlu taip semula',
          'Kalau ada gambar produk, saya masukkan sekali',
        ],
      },
      {
        title: 'Hasil yang boleh terus dihantar',
        items: [
          'PDF kemas siap cetak atau hantar kepada pembekal / pelanggan',
          'Fail Excel/CSV kalau awak nak simpan rekod',
          'Teks siap paste terus ke WhatsApp',
        ],
      },
      {
        title: 'Selepas siap',
        items: [
          'Latihan 30 minit — saya tunjuk cara guna, awak cuba depan saya',
          'Rakaman video latihan supaya staf baru boleh tengok balik',
          'Sokongan 30 hari — apa-apa rosak, saya baiki, tak kira berapa kali',
        ],
      },
    ],
    demoLabel: 'Cuba sendiri',
    demoHeading: 'Masukkan nama kedai awak',
    demoSub: 'Pilih barang, tengok Purchase Order awak terbentuk terus. Ini paparan contoh — tiada apa-apa disimpan.',
    demoField: 'Nama kedai / syarikat awak',
    demoPlaceholder: 'cth: Kedai Runcit Maju Jaya',
    demoPick: 'Pilih barang',
    demoResult: 'Purchase Order awak',
    demoEmpty: 'Pilih sekurang-kurangnya satu barang di sebelah untuk lihat hasilnya.',
    demoNote: 'Yang sebenar akan guna barang dan pembekal awak sendiri, bukan senarai contoh ni.',
    timelineLabel: '7 hari, langkah demi langkah',
    timeline: [
      { d: 'Hari 1', t: 'Kita cakap', b: 'Panggilan 30 minit. Awak tunjuk cara awak buat kerja tu sekarang. Saya tanya sampai saya faham betul-betul.' },
      { d: 'Hari 2', t: 'Data awak', b: 'Awak hantar fail atau senarai sedia ada. Saya kemas dan sahkan dengan awak kalau ada yang pelik.' },
      { d: 'Hari 3–5', t: 'Saya bina', b: 'Awak tak perlu buat apa-apa. Saya hantar link separuh siap supaya awak boleh komen awal.' },
      { d: 'Hari 6', t: 'Awak cuba', b: 'Awak guna betul-betul untuk kerja sebenar. Apa yang janggal, saya betulkan.' },
      { d: 'Hari 7', t: 'Serah', b: 'Latihan 30 minit, rakaman video, dan link kekal milik awak. Sokongan 30 hari bermula.' },
    ],
    exLabel: 'Tak termasuk dalam pakej ini',
    excludes: [
      'Login berasingan untuk ramai staf dengan hak akses berbeza',
      'Sambungan ke Shopee, TikTok, atau POS sedia ada',
      'Lebih daripada satu alat',
      'Website penuh untuk pelanggan',
    ],
    upsell: 'Perlukan mana-mana di atas? Itu pakej ASAS atau OPERASI.',
    casesLabel: 'Kajian kes',
    casesHeading: 'Contoh sebenar: 10 CAMP, kedai saya sendiri',
    casesSub: '10 CAMP import peralatan berkhemah dari China dan jual di kedai, Shopee dan TikTok. Tiga senario di bawah datang terus dari operasi harian tu. Sistem awak nanti ikut bisnes awak pula.',
    caseEls: { pain: 'Masalah asal', fix: 'Solusi', result: 'Hasil akhir' },
    cases: [
      {
        name: 'KosDarat',
        tag: 'Kalkulator kos mendarat kontena',
        pain: 'Setiap kali kontena sampai, kos sebenar per unit dikira dalam Excel bersepah: harga kilang dalam RMB, kos forwarder, duti dan SST, kadar tukaran. Harga jual di-set ikut agakan, dan ada SKU yang rupanya dijual bawah kos.',
        fix: 'Satu alat: paste senarai SKU dan harga RMB dari fail pembekal, masukkan kos kontena dan kadar duti. Alat agih semua kos ikut nisbah dan kira kos mendarat sebenar per unit, siap cadangan harga jual pada 3 tahap margin.',
        result: 'PDF costing sheet per kontena, Excel kos per SKU siap import ke POS, dan teks ringkasan untuk WhatsApp. Jimat lebih kurang 3 jam setiap kontena, dan tiada lagi SKU terjual bawah kos.',
      },
      {
        name: 'PO Kilang',
        tag: 'Penjana PO pembekal China',
        pain: 'Order restock dibuat dalam WeChat: screenshot Excel, taip model manual. Model yang sama ada 3 varian; kilang pernah hantar varian salah dan satu palet ruang kontena terbuang.',
        fix: 'Katalog SKU 10 CAMP dengan gambar produk. Pilih item, tetapkan qty ikut MOQ; alat kira jumlah RMB dan anggaran CBM supaya muatan kontena boleh dirancang sebelum order dihantar.',
        result: 'PDF Purchase Order bergambar dengan nombor siri, salinan Excel, dan teks siap paste ke WeChat. Silap varian jatuh ke sifar sebab setiap baris order ada gambar.',
      },
      {
        name: 'Terima Kontena',
        tag: 'Semakan penerimaan stok atas telefon',
        pain: 'Bila kontena sampai gudang, staf kira kotak atas kertas pack-list. Selisih hanya ditemui berbulan kemudian masa stock count, dah terlambat nak tuntut pada kilang atau forwarder.',
        fix: 'Alat dimuatkan dengan pack-list kontena. Staf gudang tap qty sebenar diterima atas telefon, tanda item rosak dan snap gambar. Alat banding automatik dengan PO dan senaraikan semua selisih.',
        result: 'PDF laporan penerimaan bertarikh sebagai bukti tuntutan, Excel selisih sahaja, dan notifikasi WhatsApp terus ke bos. Tuntutan pada kilang disokong bukti dalam 24 jam, bukan 3 bulan.',
      },
    ],
    faq: [
      { q: 'Saya tak reti teknologi. Boleh guna ke?', a: 'Boleh. Alat ni dibuat untuk orang yang sibuk jaga kedai, bukan untuk orang IT. Kalau awak boleh guna WhatsApp, awak boleh guna ini. Latihan 30 minit tu pun biasanya lebih daripada cukup.' },
      { q: 'Data saya selamat?', a: 'Alat ni milik awak sepenuhnya. Saya tak jual data, tak kongsi dengan sesiapa. Kalau kerja tu tak perlukan internet, saya boleh buat ia jalan tanpa sambungan langsung.' },
      { q: 'Kalau saya nak tambah benda lepas siap?', a: 'Boleh. Perubahan kecil dalam 30 hari pertama biasanya saya buat terus. Tambahan besar jadi kerja berasingan, dan saya beritahu harga sebelum mula — tiada bil terkejut.' },
      { q: 'Kenapa 7 hari je? Bunyi macam terlalu cepat.', a: 'Sebab skopnya sengaja kecil — satu kerja, satu alat. Saya juga guna semula komponen yang saya dah bina sebelum ni. Yang lambat biasanya bukan kerja bina, tapi skop yang tak pernah berhenti membesar.' },
    ],
  },
  en: {
    kicker: 'Package 01',
    name: 'KILAT',
    promise: 'One painful manual job — I turn it into a tool, delivered in 7 days.',
    sub: 'Not a big system. One tool that does one job properly. You use it from day one.',
    signsLabel: 'Signs you need this',
    signs: [
      'There\'s one task you repeat every week, by hand, and you dread it',
      'Your information lives in a spreadsheet that\'s painful to use when you\'re busy',
      'You type the same thing over and over in WhatsApp',
      'Things get mistyped, miscounted, or missed entirely',
    ],
    getsLabel: 'What you get',
    getsGroups: [
      {
        title: 'The tool itself',
        items: [
          'One tool with its own link — opens on phone, tablet or laptop',
          'Nothing to install, no accounts to create, no new app to teach staff',
          'Built to work on a phone screen first, because that\'s what people actually use',
          'Your work saves itself — close it, come back, everything is still there',
        ],
      },
      {
        title: 'Your data goes in once',
        items: [
          'I take your existing list — Excel, Google Sheets, PDF, or a WhatsApp list',
          'I clean and structure it, so you never retype anything',
          'Product photos included where you have them',
        ],
      },
      {
        title: 'Output you can send immediately',
        items: [
          'A clean PDF ready to print or send to a supplier or customer',
          'An Excel/CSV file if you keep your own records',
          'Text ready to paste straight into WhatsApp',
        ],
      },
      {
        title: 'After delivery',
        items: [
          '30-minute training — I show you, then you try it in front of me',
          'A recording of that session so new staff can watch it later',
          '30 days of support — anything breaks, I fix it, however many times',
        ],
      },
    ],
    demoLabel: 'Try it yourself',
    demoHeading: 'Put your shop\'s name in',
    demoSub: 'Pick a few items and watch your Purchase Order build itself. This is a preview — nothing is saved.',
    demoField: 'Your shop / company name',
    demoPlaceholder: 'e.g. Maju Jaya Mini Market',
    demoPick: 'Pick items',
    demoResult: 'Your Purchase Order',
    demoEmpty: 'Pick at least one item on the left to see the result.',
    demoNote: 'The real one uses your own products and suppliers, not this sample list.',
    timelineLabel: 'Seven days, step by step',
    timeline: [
      { d: 'Day 1', t: 'We talk', b: 'A 30-minute call. You show me how you do the job today. I ask questions until I properly understand it.' },
      { d: 'Day 2', t: 'Your data', b: 'You send your existing file or list. I clean it up and check anything that looks odd with you.' },
      { d: 'Day 3–5', t: 'I build', b: 'Nothing needed from you. I send a half-finished link so you can react early.' },
      { d: 'Day 6', t: 'You test it', b: 'You use it on real work. Anything awkward, I fix.' },
      { d: 'Day 7', t: 'Handover', b: '30-minute training, a video recording, and the link is yours. 30 days of support starts.' },
    ],
    exLabel: 'Not included in this package',
    excludes: [
      'Separate logins for multiple staff with different permissions',
      'Integration with Shopee, TikTok, or an existing POS',
      'More than one tool',
      'A full public-facing website',
    ],
    upsell: 'Need any of the above? That\'s the ASAS or OPERASI package.',
    casesLabel: 'Case studies',
    casesHeading: 'Real examples: 10 CAMP, my own shop',
    casesSub: '10 CAMP imports camping gear from China and sells in-store, on Shopee and on TikTok. The three scenarios below come straight from that daily operation. Yours would follow your business.',
    caseEls: { pain: 'The problem', fix: 'The build', result: 'The result' },
    cases: [
      {
        name: 'KosDarat',
        tag: 'Container landed-cost calculator',
        pain: 'Every time a container lands, the true per-unit cost gets worked out in a messy spreadsheet: factory prices in RMB, forwarder fees, duty and SST, the exchange rate. Retail prices get set on gut feel, and some SKUs quietly sell below cost.',
        fix: 'One tool: paste the SKU list and RMB prices from the supplier file, add container costs and duty rates. The tool allocates every cost and returns the true landed cost per unit, with suggested retail prices at 3 margin levels.',
        result: 'A costing-sheet PDF per container, a per-SKU Excel ready to import into the POS, and a summary text for WhatsApp. Roughly 3 hours saved per container, and no SKU ever sells below cost again.',
      },
      {
        name: 'PO Kilang',
        tag: 'China supplier PO generator',
        pain: 'Restock orders happen over WeChat: spreadsheet screenshots, model names typed by hand. The same tent has 3 variants; the factory once shipped the wrong one and a pallet of container space was wasted.',
        fix: 'A catalogue of 10 CAMP SKUs with product photos. Pick items, set quantities against MOQs; the tool totals the RMB value and estimates CBM so the container load is planned before the order goes out.',
        result: 'A photo-per-line Purchase Order PDF with a running number, an Excel copy, and text ready to paste into WeChat. Wrong-variant shipments drop to zero because every order line carries a picture.',
      },
      {
        name: 'Terima Kontena',
        tag: 'Goods-received check on a phone',
        pain: 'When a container reaches the warehouse, staff count boxes against a paper packing list. Discrepancies only surface months later at stock count, far too late to claim against the factory or forwarder.',
        fix: 'The tool is loaded with the container packing list. Warehouse staff tap the actual quantity received on a phone, flag damaged items and snap photos. It compares everything against the PO automatically.',
        result: 'A dated goods-received PDF as claim evidence, an Excel of discrepancies only, and a WhatsApp notification straight to the boss. Claims are backed by written proof within 24 hours, not 3 months.',
      },
    ],
    faq: [
      { q: 'I\'m not technical. Can I still use it?', a: 'Yes. It\'s built for someone busy running a shop, not for an IT person. If you can use WhatsApp, you can use this. The 30-minute training is usually more than enough.' },
      { q: 'Is my data safe?', a: 'The tool is entirely yours. I don\'t sell data and I don\'t share it with anyone. If the job doesn\'t need the internet, I can build it to work with no connection at all.' },
      { q: 'What if I want to add something after it\'s done?', a: 'You can. Small changes in the first 30 days I usually just do. Bigger additions become separate work, and I tell you the price before starting — no surprise invoice.' },
      { q: 'Why only 7 days? That sounds too fast.', a: 'Because the scope is deliberately small — one job, one tool. I also reuse components I\'ve already built. What usually makes projects slow isn\'t the building, it\'s scope that never stops growing.' },
    ],
  },
}

const asas = {
  ms: {
    kicker: 'Pakej 02',
    name: 'ASAS',
    promise: 'Website yang orang jumpa awak, plus satu sistem dalaman yang awak guna setiap hari.',
    sub: 'Muka depan untuk pelanggan, dan bahagian belakang untuk awak urus kerja. Dua-dua siap sekali.',
    signsLabel: 'Tanda awak perlukan ini',
    signs: [
      'Orang tanya "ada website tak?" dan awak terpaksa hantar link Facebook',
      'Website lama awak dah bertahun tak dijaga, atau dah hilang terus',
      'Tempahan atau order masuk bersepah dalam WhatsApp dan awak hilang jejak',
      'Awak nak nampak kemas bila berurusan dengan pelanggan atau pembekal besar',
    ],
    getsLabel: 'Apa yang awak dapat',
    getsGroups: [
      {
        title: 'Website untuk pelanggan',
        items: [
          '5–8 seksyen: siapa awak, apa awak jual, kenapa pilih awak, cara hubungi',
          'Laju dan kemas atas telefon — kebanyakan pelanggan awak guna telefon',
          'SEO asas supaya nama kedai awak keluar bila orang cari dalam Google',
          'Butang WhatsApp besar — pelanggan tekan, terus masuk chat awak',
          'Gambar dan teks awak sendiri, bukan gambar stok yang orang lain pun guna',
        ],
      },
      {
        title: 'Satu sistem dalaman',
        items: [
          'Pilih satu: tempahan, order, inventori ringkas, atau purchase order',
          'Login admin — awak tambah, ubah, padam sendiri tanpa panggil saya',
          'Senarai kemas yang boleh ditapis dan dicari',
          'Boleh keluarkan laporan atau senarai dalam PDF/Excel',
        ],
      },
      {
        title: 'Selepas siap',
        items: [
          'Latihan staf 2 jam',
          'Panduan video pendek untuk setiap kerja biasa',
          'Sokongan 60 hari',
        ],
      },
    ],
    demoLabel: 'Cuba sendiri',
    demoHeading: 'Masukkan nama kedai awak',
    demoSub: 'Tengok rupa muka depan website awak dan sistem dalaman awak. Ini paparan contoh — tiada apa-apa disimpan.',
    demoField: 'Nama kedai / syarikat awak',
    demoPlaceholder: 'cth: Kedai Runcit Maju Jaya',
    demoType: 'Jenis bisnes',
    demoTypes: [
      { id: 'runcit', label: 'Kedai runcit', tag: 'Barang harian, harga jujur', cta: 'Pesan via WhatsApp' },
      { id: 'makan', label: 'Kedai makan', tag: 'Masakan rumah setiap hari', cta: 'Tempah meja' },
      { id: 'butik', label: 'Butik', tag: 'Koleksi terhad, dijahit teliti', cta: 'Tengok koleksi' },
    ],
    demoSite: 'Muka depan (apa pelanggan nampak)',
    demoAdmin: 'Sistem dalaman (apa awak nampak)',
    demoNote: 'Warna, gambar dan ayat sebenar akan ikut jenama awak — ini cuma rangka.',
    timelineLabel: '3–4 minggu, langkah demi langkah',
    timeline: [
      { d: 'Minggu 1', t: 'Faham & skop', b: 'Kita kunci apa yang website perlu buat dan sistem mana yang paling berbaloi untuk awak.' },
      { d: 'Minggu 2', t: 'Reka bentuk', b: 'Saya tunjuk rupa sebenar sebelum bina penuh. Awak komen, saya ubah.' },
      { d: 'Minggu 3', t: 'Bina', b: 'Website dan sistem dibina. Awak dapat link untuk tengok kemajuan bila-bila.' },
      { d: 'Minggu 4', t: 'Uji & serah', b: 'Awak dan staf cuba betul-betul, saya betulkan, lepas tu latihan 2 jam dan serah.' },
    ],
    exLabel: 'Tak termasuk dalam pakej ini',
    excludes: [
      'Sambungan ke Shopee / TikTok / Lazada (jadi tambahan berasingan)',
      'Aplikasi telefon untuk muat turun',
      'Lebih daripada satu sistem dalaman',
      'Sistem bayaran dalam talian',
    ],
    upsell: 'Perlukan semua sekali dalam satu sistem? Itu pakej OPERASI.',
    casesLabel: 'Kajian kes',
    casesHeading: 'Contoh sebenar: 10 CAMP, kedai saya sendiri',
    casesSub: '10 CAMP import peralatan berkhemah dari China dan jual di kedai, Shopee dan TikTok. Tiga senario di bawah datang terus dari operasi harian tu. Sistem awak nanti ikut bisnes awak pula.',
    caseEls: { pain: 'Masalah asal', fix: 'Solusi', result: 'Hasil akhir' },
    cases: [
      {
        name: '10 CAMP Borong',
        tag: 'Website borong + sistem sebut harga',
        pain: 'Agen dan kedai outdoor tanya harga borong satu-satu di WhatsApp. Setiap pertanyaan makan 20 hingga 30 minit staf, senarai harga yang beredar ada 4 versi lama, dan tiada rekod siapa pernah bertanya.',
        fix: 'Website 6 seksyen: katalog borong ikut kategori, jadual tier harga, syarat dan MOQ, borang permohonan agen. Sistem dalaman: setiap permohonan jadi rekod; admin lulus akaun, set tier, dan jana sebut harga rasmi dengan sekali klik.',
        result: 'Quotation PDF berjenama dengan nombor siri dan tempoh sah laku, senarai penuh prospek B2B dalam satu tempat, dan pertanyaan borong dijawab dalam 3 minit. Saluran B2B jadi aset syarikat, bukan ingatan seorang staf.',
      },
      {
        name: 'Nak Restock',
        tag: 'Laman status stok + senarai pre-order',
        pain: 'Barang panas habis seminggu selepas kontena sampai. Soalan bila-ada-stok masuk berpuluh kali sehari di WhatsApp dan komen TikTok, dijawab manual, dan bila stok tiba tiada siapa dimaklumkan. Momentum jualan hilang.',
        fix: 'Website dengan status stok jelas (Ada / Habis / Dalam Kontena) dan seksyen kontena seterusnya dengan ETA. Pelanggan tekan pre-order pada item habis dan masuk senarai tunggu ikut SKU; admin urus kontena dalam sistem dalaman.',
        result: 'Bila kontena tiba, satu klik jana senarai mesej WhatsApp siap hantar kepada setiap pelanggan yang menunggu, tersusun ikut SKU. Permintaan dah beratur sebelum stok mendarat; minggu pertama kontena jadi minggu jualan terbaik.',
      },
      {
        name: '10 CAMP Event',
        tag: 'Microsite expo + rekod jualan luar kedai',
        pain: 'Masa expo, jualan direkod atas kertas dan stok bawa-keluar bawa-balik dikira tergesa-gesa. Selepas satu event, ada unit tak berakaun dan tiada siapa tahu item mana paling laku di booth.',
        fix: 'Microsite event dengan promo khas, tarikh dan lokasi booth. Sistem dalaman: senarai stok dibawa keluar direkod dulu, staf rekod setiap jualan atas telefon di booth, dan kiraan stok balik dibanding automatik.',
        result: 'Laporan PDF post-event: jualan per SKU, per staf, per cara bayaran, dan selisih stok dikesan hari itu juga. Untung rugi sebenar expo siap dalam 24 jam selepas booth tutup.',
      },
    ],
    faq: [
      { q: 'Nama domain dan hosting macam mana?', a: 'Atas nama awak sendiri, bukan nama saya — supaya awak tak terikat dengan saya. Untuk bisnes kecil kosnya biasanya percuma hingga sangat murah. Saya tolong setupkan dan saya tak ambil untung atasnya.' },
      { q: 'Saya boleh ubah teks sendiri lepas ni?', a: 'Untuk sistem dalaman, ya — awak ada login admin. Untuk teks website, perubahan kecil saya buat percuma dalam tempoh sokongan. Kalau awak nak ubah sendiri sepenuhnya, cakap awal, saya boleh bina cara tu.' },
      { q: 'Kalau nanti saya nak naik ke sistem penuh?', a: 'Kerja pakej ni tak terbuang. Website dan sistem awak jadi asas, dan kita tambah bahagian lain di atasnya. Awak bayar beza, bukan mula semula.' },
    ],
  },
  en: {
    kicker: 'Package 02',
    name: 'ASAS',
    promise: 'A website so people can find you, plus one internal system you actually use daily.',
    sub: 'A front for customers and a back for you. Both delivered together.',
    signsLabel: 'Signs you need this',
    signs: [
      'People ask "do you have a website?" and you send them a Facebook link',
      'Your old site hasn\'t been touched in years, or has disappeared entirely',
      'Bookings or orders arrive scattered across WhatsApp and you lose track',
      'You want to look credible when dealing with bigger customers or suppliers',
    ],
    getsLabel: 'What you get',
    getsGroups: [
      {
        title: 'A website for your customers',
        items: [
          '5–8 sections: who you are, what you sell, why you, how to reach you',
          'Fast and clean on a phone — that\'s where most of your customers are',
          'Basic SEO so your name shows up when people search Google',
          'A big WhatsApp button — customers tap it and land in your chat',
          'Your own photos and words, not stock images everyone else uses',
        ],
      },
      {
        title: 'One internal system',
        items: [
          'Pick one: bookings, orders, light inventory, or purchase orders',
          'Admin login — you add, edit and delete without calling me',
          'A clean list you can search and filter',
          'Export a report or list as PDF/Excel',
        ],
      },
      {
        title: 'After delivery',
        items: [
          '2 hours of staff training',
          'Short video guides for each routine task',
          '60 days of support',
        ],
      },
    ],
    demoLabel: 'Try it yourself',
    demoHeading: 'Put your shop\'s name in',
    demoSub: 'See how your front page and your internal system would look. This is a preview — nothing is saved.',
    demoField: 'Your shop / company name',
    demoPlaceholder: 'e.g. Maju Jaya Mini Market',
    demoType: 'Type of business',
    demoTypes: [
      { id: 'runcit', label: 'Grocery shop', tag: 'Everyday goods, honest prices', cta: 'Order on WhatsApp' },
      { id: 'makan', label: 'Restaurant', tag: 'Home cooking, every day', cta: 'Book a table' },
      { id: 'butik', label: 'Boutique', tag: 'Small batches, carefully made', cta: 'View collection' },
    ],
    demoSite: 'Front page (what customers see)',
    demoAdmin: 'Internal system (what you see)',
    demoNote: 'Real colours, photos and words follow your brand — this is only the skeleton.',
    timelineLabel: '3–4 weeks, step by step',
    timeline: [
      { d: 'Week 1', t: 'Understand & scope', b: 'We lock down what the site must do and which internal system earns its keep for you.' },
      { d: 'Week 2', t: 'Design', b: 'I show you the real look before building it fully. You react, I adjust.' },
      { d: 'Week 3', t: 'Build', b: 'Site and system get built. You get a link to check progress any time.' },
      { d: 'Week 4', t: 'Test & hand over', b: 'You and your staff use it for real, I fix what\'s awkward, then 2 hours of training and handover.' },
    ],
    exLabel: 'Not included in this package',
    excludes: [
      'Shopee / TikTok / Lazada integration (priced separately)',
      'A downloadable mobile app',
      'More than one internal system',
      'Online payment processing',
    ],
    upsell: 'Need all of it in one system? That\'s the OPERASI package.',
    casesLabel: 'Case studies',
    casesHeading: 'Real examples: 10 CAMP, my own shop',
    casesSub: '10 CAMP imports camping gear from China and sells in-store, on Shopee and on TikTok. The three scenarios below come straight from that daily operation. Yours would follow your business.',
    caseEls: { pain: 'The problem', fix: 'The build', result: 'The result' },
    cases: [
      {
        name: '10 CAMP Borong',
        tag: 'Wholesale site + quotation system',
        pain: 'Agents and outdoor shops ask for wholesale prices one by one on WhatsApp. Each enquiry eats 20 to 30 minutes of staff time, 4 outdated price lists are floating around, and nobody knows who ever asked.',
        fix: 'A 6-section website: wholesale catalogue by category, price-tier table, terms and MOQs, an agent application form. Internally: every application becomes a record; admin approves accounts, sets tiers, and generates an official quotation in one click.',
        result: 'A branded quotation PDF with a serial number and validity period, every B2B prospect in one list, and wholesale enquiries answered in 3 minutes. The B2B channel becomes a company asset instead of one staff member\u2019s memory.',
      },
      {
        name: 'Nak Restock',
        tag: 'Stock-status site + pre-order list',
        pain: 'Hot items sell out within a week of a container landing. When-will-it-restock questions arrive dozens of times a day on WhatsApp and TikTok comments, answered by hand, and nobody gets told when stock arrives. Sales momentum dies.',
        fix: 'A site with honest stock status (In stock / Sold out / On the container) and a next-container section with ETA. Customers tap pre-order on sold-out items and join a per-SKU waiting list; admin manages containers in the internal system.',
        result: 'When the container lands, one click generates ready-to-send WhatsApp messages for every waiting customer, sorted by SKU. Demand queues up before stock arrives; the first week of every container becomes the best sales week.',
      },
      {
        name: '10 CAMP Event',
        tag: 'Expo microsite + off-site sales log',
        pain: 'At expos, sales get written on paper and the stock taken out and brought back is counted in a rush. After one event, units went unaccounted for and nobody knew which items actually moved at the booth.',
        fix: 'An event microsite with special promos, dates and booth location. Internally: the stock taken out is listed first, staff log every sale on a phone at the booth, and the returning stock count is compared automatically.',
        result: 'A post-event PDF: sales per SKU, per staff, per payment method, with stock discrepancies caught the same day. The true profit and loss of an expo is ready within 24 hours of the booth closing.',
      },
    ],
    faq: [
      { q: 'What about the domain and hosting?', a: 'They stay in your name, not mine — so you\'re never stuck with me. For a small business the cost is usually free to very cheap. I set it up and take no cut of it.' },
      { q: 'Can I edit the text myself afterwards?', a: 'For the internal system, yes — you have an admin login. For website text, small changes I make free during the support window. If you want full self-editing, say so early and I\'ll build it that way.' },
      { q: 'What if I want to move up to a full system later?', a: 'None of this work is wasted. Your site and system become the foundation and we build the rest on top. You pay the difference, not the whole thing again.' },
    ],
  },
}

const operasi = {
  ms: {
    kicker: 'Pakej 03',
    name: 'OPERASI',
    promise: 'Stok, order, kos dan laporan — semua dalam satu sistem yang awak miliki.',
    sub: 'Ini yang saya bina untuk kedai saya sendiri. Bukan teori, bukan demo — benda yang staf saya guna setiap hari.',
    signsLabel: 'Tanda awak perlukan ini',
    signs: [
      'Awak tak tahu barang mana yang betul-betul untung dan mana yang makan duit awak',
      'Stok atas sistem tak sama dengan stok atas rak',
      'Setiap bulan awak habiskan berhari-hari kira-kira sebelum tahu untung rugi',
      'Awak bayar subscription bulanan untuk platform yang awak dah terlebih besar',
      'Staf ramai, dan awak perlu kawal siapa boleh tengok apa',
    ],
    getsLabel: 'Apa yang awak dapat',
    getsGroups: [
      {
        title: 'Satu sistem, semua bahagian',
        items: [
          'Kaunter jualan (POS) yang staf boleh guna tanpa latihan panjang',
          'Inventori yang tolak stok sendiri bila barang terjual',
          'Order dan penghantaran dalam satu tempat',
          'Kos sebenar setiap barang — termasuk kos hantar dan duti',
          'Laporan untung rugi yang awak boleh percaya',
        ],
      },
      {
        title: 'Kawalan staf',
        items: [
          'Banyak pengguna, hak akses ikut jawatan',
          'Kasir nampak apa yang kasir perlu, bukan kos dan margin awak',
          'Rekod siapa buat apa dan bila',
        ],
      },
      {
        title: 'Sambungan luar',
        items: [
          'Shopee, TikTok atau Lazada — stok kemas kini dua hala',
          'Order marketplace masuk sekali dengan order kedai',
          'Duit settlement dipadan dengan jualan sebenar',
        ],
      },
      {
        title: 'Pindah masuk',
        items: [
          'Data lama awak dipindahkan — Excel, sistem lama, atau platform subscription',
          'Saya sahkan angka dengan awak sebelum kita tukar sepenuhnya',
          'Kedai awak tak berhenti beroperasi masa pertukaran',
        ],
      },
    ],
    demoLabel: 'Cuba sendiri',
    demoHeading: 'Masukkan nama kedai awak',
    demoSub: 'Tengok rupa papan pemuka awak pada pagi hari biasa. Angka di bawah semuanya rekaan — ini paparan contoh sahaja.',
    demoField: 'Nama kedai / syarikat awak',
    demoPlaceholder: 'cth: Kedai Runcit Maju Jaya',
    demoGreet: 'Selamat pagi',
    demoStats: {
      sales: 'Jualan hari ini', orders: 'Order belum pack',
      low: 'Stok hampir habis', profit: 'Untung hari ini',
    },
    demoChart: 'Jualan 7 hari lepas',
    demoLow: 'Perlu order semula',
    demoLeft: 'tinggal',
    demoNeed: 'cadang order',
    demoNote: 'Yang sebenar guna angka kedai awak, dan boleh dibuka dari telefon awak setiap pagi.',
    timelineLabel: '2–3 bulan, ikut fasa',
    timeline: [
      { d: 'Fasa 1', t: 'Kira & rancang', b: 'Saya masuk dalam cara kerja awak sekarang, kira apa yang patut, dan kunci apa yang dibina dahulu. Bil 30%.' },
      { d: 'Fasa 2', t: 'Teras', b: 'Stok, jualan dan kos dibina dan diuji dengan data sebenar awak. Bil 30%.' },
      { d: 'Fasa 3', t: 'Sambungan', b: 'Marketplace, laporan dan hak akses staf. Pindah data lama masuk.' },
      { d: 'Fasa 4', t: 'Tukar & serah', b: 'Kita tukar sepenuhnya, saya ada sepanjang minggu pertama. Latihan penuh. Bil 40%.' },
    ],
    exLabel: 'Perkara yang biasa disalah faham',
    excludes: [
      'Ini bukan kerja seminggu — sistem sebesar ni ambil masa dan penglibatan awak',
      'Saya perlukan data awak yang sebenar, bukan anggaran',
      'Aplikasi telefon dan ejen AI adalah tambahan berasingan',
      'Perkakasan (mesin, printer, scanner) awak beli sendiri — saya cadangkan yang mana',
    ],
    upsell: 'Belum pasti perlu sebesar ini? Mula dengan KILAT dahulu, naik bila awak dah nampak hasilnya.',
    casesLabel: 'Kajian kes',
    casesHeading: 'Contoh sebenar: 10 CAMP, kedai saya sendiri',
    casesSub: '10 CAMP import peralatan berkhemah dari China dan jual di kedai, Shopee dan TikTok. Tiga senario di bawah datang terus dari operasi harian tu. Sistem awak nanti ikut bisnes awak pula.',
    caseEls: { pain: 'Masalah asal', fix: 'Solusi', result: 'Hasil akhir' },
    cases: [
      {
        name: '10 CAMP Central',
        tag: 'POS + inventori + sync Shopee/TikTok dua hala',
        pain: 'Jualan berjalan di 3 saluran (kedai, Shopee, TikTok Shop) tapi stok diurus berasingan. Staf kemaskini baki manual setiap malam; kelewatan beberapa jam cukup untuk double-sell unit terakhir. Refund, penalti platform, rating jatuh.',
        fix: 'Satu sistem: POS kaunter dengan resit dan pelbagai cara bayar, inventori pusat 600+ SKU dengan lokasi bin gudang, dan integrasi dua hala. Jualan mana-mana saluran tolak stok pusat serta-merta; kemaskini stok ditolak balik ke Shopee dan TikTok. Peranan berlapis: cashier jual sahaja, manager urus stok, bos nampak semua. Data lama dimigrasi masuk.',
        result: 'Kemaskini manual malam-malam dihapuskan (1 hingga 2 jam sehari), double-sell jatuh hampir sifar, dan digest WhatsApp automatik setiap petang: jualan per saluran, AOV, item hampir habis. Satu angka stok, satu versi kebenaran.',
      },
      {
        name: 'ImportOps',
        tag: 'Rantaian import penuh: PO, kontena, gudang, margin',
        pain: 'Kitaran import melibatkan 4 orang dan 6 fail Excel berbeza: PO kilang di satu tempat, tracking vessel dalam email forwarder, penerimaan gudang atas kertas, kos mendarat dikira kemudian. Tiada siapa boleh jawab pantas kontena mana paling untung tahun ini.',
        fix: 'Modul bersambung dalam satu sistem: database pembekal dengan lead time sebenar dikira dari sejarah, PO berstatus dari draf hingga tiba, tracking kontena dengan dokumen custom dilampirkan, GRN gudang atas telefon, kos mendarat auto-agih terus jadi COGS, dan laporan margin per SKU, per kontena, per pembekal. Setiap peranan nampak skrin masing-masing sahaja.',
        result: 'Soalan berapa-kos-sebenar-barang-ni dijawab dalam 5 saat, bukan selepas sesi Excel sejam. Keputusan restock dibuat atas margin dan lead time sebenar, dan semua dokumen import tersusun ikut kontena bila audit sampai.',
      },
      {
        name: '10 CAMP HQ',
        tag: 'Multi-lokasi + portal agen + operasi staf',
        pain: 'Cawangan kedua dirancang dan rangkaian agen semakin besar, tapi transfer stok tiada rekod, order agen ikut chat, cuti dan claim staf diurus dalam WhatsApp group. Bila skala naik, kekacauan ikut naik.',
        fix: 'Sistem induk: stok per lokasi dengan transfer disahkan penerima, portal agen yang login sendiri (harga ikut tier, had kredit, baki hutang, order lulus terus tolak stok gudang), roster ikut lokasi serta claim staf dengan kelulusan dalam sistem. POS dan sync marketplace kekal sebagai teras.',
        result: 'Buka cawangan baru bermakna tambah satu lokasi dalam sistem, bukan bina proses dari kosong. Order agen masuk sendiri 24 jam tanpa staf menaip. Satu dashboard untuk semua lokasi, agen dan marketplace, dengan digest harian ke telefon bos.',
      },
    ],
    faq: [
      { q: 'Kenapa saya patut pilih awak dan bukan sistem siap pakai?', a: 'Sistem siap pakai bagus kalau bisnes awak sama macam bisnes orang lain. Saya bina 10 CAMP sendiri sebab tiada platform yang faham cara kami bekerja, dan kami berhenti bayar subscription selama-lamanya. Kalau sistem siap pakai memang muat untuk awak, saya akan cakap terus — lebih baik awak jimat duit daripada saya ambil projek yang tak sepatutnya.' },
      { q: 'Kalau awak hilang, apa jadi pada sistem saya?', a: 'Kod dan data milik awak sepenuhnya selepas bayaran penuh. Semuanya didokumenkan supaya developer lain boleh sambung. Saya tak kunci awak pada mana-mana platform, dan saya tak simpan apa-apa yang awak tak boleh capai.' },
      { q: 'Kedai saya tak boleh tutup untuk tukar sistem.', a: 'Tak perlu tutup. Kita jalan dua sistem serentak dalam tempoh peralihan, saya sahkan angka padan, baru kita matikan yang lama. Itu cara saya buat untuk kedai saya sendiri.' },
      { q: 'Berapa saya jimat sebenarnya?', a: 'Bergantung bisnes awak. Dua tempat biasa: subscription platform yang awak bayar setiap bulan selama-lamanya, dan jam kerja admin yang hilang setiap minggu. Dalam sesi diagnosis, kita kira nombor awak sendiri — bukan nombor pukul rata.' },
    ],
  },
  en: {
    kicker: 'Package 03',
    name: 'OPERASI',
    promise: 'Stock, orders, costing and reporting — one system, and you own it.',
    sub: 'This is what I built for my own shop. Not theory, not a demo — the thing my staff use every day.',
    signsLabel: 'Signs you need this',
    signs: [
      'You don\'t know which products actually make money and which quietly eat it',
      'Stock in the system doesn\'t match stock on the shelf',
      'Every month you lose days to arithmetic before you know if you made a profit',
      'You\'re paying a monthly subscription for a platform you\'ve outgrown',
      'You have several staff and need to control who sees what',
    ],
    getsLabel: 'What you get',
    getsGroups: [
      {
        title: 'One system, all the parts',
        items: [
          'A point of sale your staff can use without lengthy training',
          'Inventory that decrements itself as things sell',
          'Orders and fulfilment in one place',
          'True cost per product — including freight and duties',
          'Profit and loss reporting you can actually trust',
        ],
      },
      {
        title: 'Staff control',
        items: [
          'Multiple users with role-based permissions',
          'Cashiers see what cashiers need, not your costs and margins',
          'A record of who did what, and when',
        ],
      },
      {
        title: 'Outside connections',
        items: [
          'Shopee, TikTok or Lazada — stock updates both ways',
          'Marketplace orders land beside your in-store orders',
          'Settlement money reconciled against actual sales',
        ],
      },
      {
        title: 'Moving in',
        items: [
          'Your old data migrated — spreadsheets, a legacy system, or a subscription platform',
          'I reconcile the numbers with you before we switch fully',
          'Your shop keeps trading throughout the changeover',
        ],
      },
    ],
    demoLabel: 'Try it yourself',
    demoHeading: 'Put your shop\'s name in',
    demoSub: 'See what your dashboard looks like on an ordinary morning. Every number below is invented — this is a preview only.',
    demoField: 'Your shop / company name',
    demoPlaceholder: 'e.g. Maju Jaya Mini Market',
    demoGreet: 'Good morning',
    demoStats: {
      sales: 'Sales today', orders: 'Orders to pack',
      low: 'Running low', profit: 'Profit today',
    },
    demoChart: 'Last 7 days',
    demoLow: 'Needs reordering',
    demoLeft: 'left',
    demoNeed: 'suggested order',
    demoNote: 'The real one uses your numbers, and opens on your phone every morning.',
    timelineLabel: '2–3 months, in phases',
    timeline: [
      { d: 'Phase 1', t: 'Count & plan', b: 'I get inside how you work today, count what needs counting, and lock what gets built first. 30% billed.' },
      { d: 'Phase 2', t: 'The core', b: 'Stock, sales and costing built and tested against your real data. 30% billed.' },
      { d: 'Phase 3', t: 'Connections', b: 'Marketplaces, reporting and staff permissions. Old data migrated in.' },
      { d: 'Phase 4', t: 'Switch & hand over', b: 'We cut over fully and I\'m present through the first week. Full training. 40% billed.' },
    ],
    exLabel: 'Things people commonly misunderstand',
    excludes: [
      'This isn\'t a one-week job — a system this size takes time and your involvement',
      'I need your real data, not estimates',
      'A mobile app and AI agents are separate additions',
      'Hardware (terminals, printers, scanners) you buy yourself — I\'ll tell you which',
    ],
    upsell: 'Not sure you need something this big? Start with KILAT and move up once you see it working.',
    casesLabel: 'Case studies',
    casesHeading: 'Real examples: 10 CAMP, my own shop',
    casesSub: '10 CAMP imports camping gear from China and sells in-store, on Shopee and on TikTok. The three scenarios below come straight from that daily operation. Yours would follow your business.',
    caseEls: { pain: 'The problem', fix: 'The build', result: 'The result' },
    cases: [
      {
        name: '10 CAMP Central',
        tag: 'POS + inventory + two-way Shopee/TikTok sync',
        pain: 'Sales run through 3 channels (the shop, Shopee, TikTok Shop) but stock lives in separate silos. Staff update balances by hand every night; a few hours of lag is enough to double-sell the last unit. Refunds, platform penalties, falling ratings.',
        fix: 'One system: a counter POS with receipts and multiple payment methods, central inventory for 600+ SKUs with warehouse bin locations, and two-way integration. A sale on any channel deducts central stock instantly; stock updates push back to Shopee and TikTok. Layered roles: cashiers sell, managers handle stock, the boss sees everything. Old data fully migrated in.',
        result: 'The nightly manual update disappears (1 to 2 hours a day), double-selling drops to near zero, and an automatic WhatsApp digest lands every evening: sales per channel, AOV, items running low. One stock number, one version of the truth.',
      },
      {
        name: 'ImportOps',
        tag: 'Full import chain: PO, container, warehouse, margin',
        pain: 'The import cycle involves 4 people and 6 different spreadsheets: factory POs in one place, vessel tracking in forwarder emails, warehouse receiving on paper, landed cost calculated afterwards. Nobody can quickly answer which container made the most money this year.',
        fix: 'Connected modules in one system: a supplier database with real lead times computed from history, POs with status from draft to arrived, container tracking with customs documents attached, phone-based goods receiving, landed cost auto-allocated straight into COGS, and margin reports per SKU, per container, per supplier. Each role sees only its own screens.',
        result: 'What-does-this-actually-cost gets answered in 5 seconds instead of an hour of spreadsheet work. Restock decisions run on real margins and real lead times, and every import document is filed by container when the audit comes.',
      },
      {
        name: '10 CAMP HQ',
        tag: 'Multi-location + agent portal + staff operations',
        pain: 'A second branch is planned and the agent network keeps growing, but stock transfers have no records, agent orders live in chat, and staff leave and claims are handled in a WhatsApp group. As scale goes up, chaos goes up with it.',
        fix: 'A headquarters system: stock per location with receiver-confirmed transfers, a self-serve agent portal (tiered pricing, credit limits, outstanding balance, approved orders deduct warehouse stock directly), location-based rosters and staff claims with in-system approval. The POS and marketplace sync stay as the core.',
        result: 'Opening a branch means adding one location in the system, not building a process from scratch. Agent orders arrive on their own around the clock with no staff typing. One dashboard for every location, agent and marketplace, with a daily digest to the boss.',
      },
    ],
    faq: [
      { q: 'Why you instead of an off-the-shelf system?', a: 'Off-the-shelf is great when your business works like everyone else\'s. I built 10 CAMP\'s system myself because no platform understood how we actually work, and we stopped paying subscriptions forever. If an off-the-shelf product genuinely fits you, I\'ll tell you straight — better you save the money than I take a project I shouldn\'t.' },
      { q: 'What happens to my system if you disappear?', a: 'The code and data are entirely yours once paid. Everything is documented so another developer can pick it up. I don\'t lock you into any platform and I hold nothing you can\'t reach yourself.' },
      { q: 'My shop can\'t close for a system change.', a: 'It doesn\'t need to. We run both systems side by side through the transition, I verify the numbers match, and only then do we retire the old one. That\'s how I did it for my own shop.' },
      { q: 'How much do I actually save?', a: 'It depends on your business. Two usual places: the platform subscription you pay every month forever, and the admin hours that vanish each week. In the diagnostic session we work out your numbers, not an average.' },
    ],
  },
}

export const PAGES = { kilat, asas, operasi }
export const pageFor = (slug, lang) => (PAGES[slug] ? PAGES[slug][lang] || PAGES[slug].ms : null)
